# Generated by Django 3.2.15 on 2022-08-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('publication_date', models.DateField()),
                ('author', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'book',
                'managed': True,
            },
        ),
    ]
